### ISSUE TITLE
Clicking links in playlist opens YouTube

### ISSUE THREAD

**Issue by ianbruton** [rblstr/flock#1]
Clicking on a link in the playlist link list opens YouTube instead of skipping to that song in the player. This is inconvenient as it navigates away from the playlist page and a user may lose their position in the playlist as a result.

It would be much more convenient to have the link jump to that song in the playlist.

Solution:
When a user clicks a link in the playlist, either:
- Stop the player and open that link in a new tab
- Skip to that song in the playlist present in the player

**Comment by okeeffe** [comment]
My vote is for option 2, but it needs to be made clear that is what will happen with appropriate styling. I might put in a pull request and try styling shit up?

**Comment by rblstr** [comment]
@rorokeeffe go for it man

**Comment by ianbruton** [comment]
I helped!

**Comment by rblstr** [comment]
Thanks for the suggestion @ianbruton, this worked out great.
