### ISSUE TITLE
Update page title to reflect currently playing song

### ISSUE THREAD

**Issue by okeeffe** [rblstr/flock#11]
Flock - Onra - I Wanna Go Back

...in the title bar when something is playing

**Comment by rblstr** [comment]
Where is it going to get the title from? YouTube video? Reddit link title?

This seems like a job for front-end (ie you :wink: ), YouTube event listeners for the embedded player changing song. Don't know how you'll get the title though...

**Comment by rblstr** [comment]
We can use the following API functions in JS:
- player.getVideoUrl():String
- player.getVideoEmbedCode():String

We'd have to then use the YouTube API to query that video's information and grab the title from that.

**Comment by rblstr** [comment]
See https://developers.google.com/youtube/v3/docs/videos/list

**Comment by okeeffe** [comment]
Cool beans I'll take a look.

**Comment by rblstr** [comment]
Actually hold off for a bit. Finish up a first pass of the frontpage, we can merge it in then you can move to this repository.

We can discuss branching strategy then.
