### ISSUE TITLE
Sorting order and default sort parameter

### ISSUE THREAD

**Issue by rblstr** [rblstr/flock#16]
Currently the default sort is `top`, should this be changed to `hot`?

@rorokeeffe I think the order of buttons should go "Hot" (default), "Top", "Time".

Right now "Hot" is next to "Time" when "Top" is active, reads just a bit wrong. Also, can we integrate the "Time" parameter into a drop-down checklist on the "Top" button? So they become one?

**Comment by okeeffe** [comment]
I'll see what I can do. The UI for that combined dropdown is the only tricky part.
