### ISSUE TITLE
Expand footer

### ISSUE THREAD

**Issue by rblstr** [rblstr/flock#18]
Currently there's links to me and @rorokeeffe, but we should probably have some smaller print for contact, and Github / issues link for bug reporting.

**Comment by okeeffe** [comment]
We can link to the project yeah. People can get in touch with us through Github though. We could do the Github project link, then have the @ links be to our Twitters.

**Comment by rblstr** [comment]
# with :heart: from @rblstr and @rorokeeffe

### Check out the project and submit bugs on [GitHub](https://github.com/rblstr/flock)

Or something like that

**Comment by okeeffe** [comment]
That's pretty much exactly what I had in mind yep.
