### ISSUE TITLE
Investigate YouTube connection problems

### ISSUE THREAD

**Issue by rblstr** [rblstr/flock#19]
@rorokeeffe has been having some odd intermittent issues with not being able to select songs to play / playlist acting strange.

I suspect it may be a YouTube connection / API issue, worth investigating and if there in an error with YouTube, failing gracefully with an error message.

**Comment by okeeffe** [comment]
Nothing intermittent about it. Flat out not working in work. I'll check it at home but I'm worried.

**Comment by rblstr** [comment]
Works perfectly fine for me at work and at home, I think its something to do with your work network.

Absolutely no information in the developer console? Worth checking page source to make sure everything generated correctly.

**Comment by okeeffe** [comment]
I showed you what was in the dev console already.

![capture](https://f.cloud.github.com/assets/1760060/1868222/b2f91180-7864-11e3-98a5-2c160ce5a386.JPG)

**Comment by rblstr** [comment]
Well I think theres an `onError` callback when loading the YouTube player, try hooking into that and seeing if there's anything coming through.

**Comment by okeeffe** [comment]
Sure but the YouTube player itself actually loads and plays the playlist, it just isn't telling the page about what it's playing or allowing Javascript to influence what's playing. I'll give it an old English anyway.
