### ISSUE TITLE
Video Entry in Playlist Does not Match Currently Playing Video

### ISSUE THREAD

**Issue by CianScolard** [rblstr/flock#22]
Quick screenshot attached, playing video is "Larse - The More I Want", not matched by "White Lamp - Ride With You" in playlist on page. Hence, Youtube link etc not concurrent with currently playing music.

EDIT: It appears the entire playlist after the first few videos is out of sync.

Other notes:
- Using Chrome
- I've not manually searched for subreddit/refreshed my page in a while, just opened Chrome and hit play again.
- Swag.

![image](https://f.cloud.github.com/assets/4478225/2077957/fbe959b4-8db7-11e3-8f75-fbeb70db9344.png)

**Comment by rblstr** [comment]
Can I ask what subreddit/s you were playlisting?

**Comment by CianScolard** [comment]
Playlisting http://staging.flock.rblstr.com/?subreddits=deephouse.

Still in that session if you've anything like that going on, haven't moved. Currently paused on track # 11.

**Comment by rblstr** [comment]
Closing this issue as we cannot reproduce, YouTube and/or browser cache probably being the issue.

Will re-open if we can reproduce with confidence.
