### ISSUE TITLE
Wrong Reddit URL

### ISSUE THREAD

**Issue by okeeffe** [rblstr/flock#29]
http://http//www.reddit.com/r/futurebeats/comments/1yidz3/disclosure_lorde_and_alunageorge_perform/

^^ Check out the double http action. Hawt.

**Comment by rblstr** [comment]
**Cause**
Due to `REDDIT_URL` constant being changed for `urlopen` purposes, now track permalinks are incorrect.

**Fix**
Change the permalink format string from `http://REDDIT_URL` to just `REDDIT_URL`

**Comment by rblstr** [comment]
Offending line:
https://github.com/rblstr/flock/blob/dev/flock.py#L194
