### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by okeeffe** [rblstr/flock#4]
Add a favicon to flock such that I can find the flock tab quickly when I have way too many /r/gonewild tabs open.

Solutions:
- Add my face as a favicon

**Comment by okeeffe** [comment]
Best ninja-rewrite ever.

**Fap once, close multiple tabs**

**Comment by rblstr** [comment]
Shitty emoji placeholder, will swap out when starting to do design pass :musical_note: flock :musical_note:
