### ISSUE TITLE
I want the playlist to be made up of actual track names (or youtube video names, at least)

### ISSUE THREAD

**Issue by okeeffe** [rblstr/flock#5]
So instead of:
1. SONG SO GOOD IT WILL BLOW YOUR NUTS OFF

I want:

**4. Nas - New York State of Mind** - _from "SONG SO GOOD IT WILL BLOW YOUR NUTS OFF"_

The from section could be all clickable as the permalink.

**Comment by rblstr** [comment]
Love this idea, getting the data from YouTube might require some extra bandwidth to query but if I integrate Memcache into the app I should only take the bandwidth (and end user latency) hit once.

**Comment by rblstr** [comment]
Tried some YouTube batch requests, which seem to work but you exceed the YouTube API quota pretty quick. I'll eventually register Flock as a YouTube app but until then I'm removing this enhancement from the 0.1 milestone. I'll leave it open for future milestones.

**Comment by rblstr** [comment]
Code now supports this as of f02ac14
How these titles are presented is up to front-end design, which I'm currently deferring to @rorokeeffe
